# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Douglas Fox Writes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Douglas Fox Writes is where you can find out what's going in Dougie's head.
  Thoughts mostly on lifestyle design and digital nomadism with some extra
  random nuggets that need to be shared (so people can shoot them down).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
